services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=somewordpress
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    expose:
    - 3306
    - 33060
    networks:
    - wordpress_network

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
    - WORDPRESS_DB_HOST=db
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=wordpress
    - WORDPRESS_DB_NAME=wordpress
    labels:
    - "traefik.http.routers.blog.rule=Host(`blog.raxil.click`)"
    - "traefik.http.routers.blog.entrypoints=websecure"
    - "traefik.http.routers.blog.tls=true"
    - "traefik.docker.network=web"
    - "traefik.http.routers.website2.tls.certresolver=traefikÙ€app"
    networks:
    - wordpress_network
    - web

volumes:
  db_data:


networks:
  wordpress_network:
    driver: bridge
  web:
    external: true
