version: "3"

services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=somewordpress
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress
    networks:
    - wordpress_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wordpress", "-p$MYSQL_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
    - WORDPRESS_DB_HOST=db:3306
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=wordpress
    - WORDPRESS_DB_NAME=wordpress
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.blog.rule=Host(`blog.raxil.click`)"
    - "traefik.http.routers.blog.entrypoints=websecure"
    - "traefik.http.routers.blog.tls=true"
    - "traefik.docker.network=web"
    - "traefik.http.routers.blog.tls.certresolver=http"
    networks:
    - wordpress_network
    - web
    healthcheck:
      test: [ "CMD", "sh", "-c", "mysql -h db -u wordpress -p$WORDPRESS_DB_PASSWORD $WORDPRESS_DB_NAME -e 'SELECT 1'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  db_data:


networks:
  wordpress_network:
    driver: bridge
  web:
    external: true
